name: Main CI

on: [push]

build:
  runs-on: ubuntu-latest

  steps:
  - name: Login to Docker
    run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
  
  - uses: actions/checkout@v3

  - name: Build Docker Image
    run: docker build -t ${{ secrets.DOCKER_PROJECT }}:${GITHUB_REF_NAME} -f Dockerfile .

  - name: Push image to Dockerhub
    run: docker push ${{ secrets.DOCKER_PROJECT }}:${GITHUB_REF_NAME}